---

- name: Create Confluence data directory
  file:
    path: "{{ confluence_docker_data_dir }}"
    state: directory

- name: Create Confluence container
  docker_container:
    name: confluence
    image: "atlassian/confluence-server:{{ confluence_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - 8090:8090
      - 8091:8091
    volumes:
      - "{{ confluence_docker_data_dir }}:/var/atlassian/application-data/confluence"
