---

- name: Create Confluence data directory
  file:
    path: "{{ confluence_docker_data_dir }}"
    state: directory

- name: Create Confluence container
  docker_container:
    name: confluence
    image: "atlassian/confluence-server:{{ confluence_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    networks: "{{ omit if not confluence_docker_network else confluence_docker_network }}"
    published_ports: "{{ omit if not confluence_docker_exposed_ports else confluence_docker_exposed_ports }}"
    volumes:
      - "{{ confluence_docker_data_dir }}:/var/atlassian/application-data/confluence"
