---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-confluence-docker
    image: ubuntu:${UBUNTU_IMAGE_TAG:-latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  options:
    v: false
  lint:
    name: ansible-lint
    options:
      x: ["E204"]
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
